### ISSUE TITLE
can code be editted in seperate files?

### ISSUE THREAD

**Issue by ideapad2009** [DD4WH/Teensy-ConvolutionSDR#12]
Dear Author:
    I want to porting your program in stm32h7 device with msi001 tunner ，but there is  difficulty to read so much code in a single file.Can program be classified  into cpp&header files base on the  function ?

**Comment by DD4WH** [comment]
Yes, that would be perfect to have a nicer overview. However, I do not plan to do it.
if you plan to do it, go ahead!
However, if you are going to port it to the STM32H7 anyway, maybe you can save some time and effort by looking at UHSDR, which is a fully mature Transceiver software specifically designed for the STM32H7 (however: no convolution filtering (yet ;-))):

https://github.com/df8oe/UHSDR/wiki

**Comment by ideapad2009** [comment]
Emm..You know malahit sdr hardware platform is very convenient as a portable sdr receiver.But their firmware is commercial and not free.So I plan to search a open source solution and  port it.
